name: BUILD

on:
  push:
  schedule:
    - cron:  '1 */8 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [pycharm-professional, deepin-wine-wechat, yesplaymusic, yesplaymusic-electron, discord_arch_electron, osu-lazer]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: ./build-aur-action
        with:
          repo-name: ${{ matrix.repos }}

      - id: pkgname
        working-directory: ${{ matrix.repos }}
        run: echo ::set-output name=pkgname::$(ls *-x86_64.pkg.*)

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'repo-builder'
          server: ${{ secrets.REPO_BUILDER_HOST }}
          ssh_private_key: ${{ secrets.REPO_BUILDER_PRIVKEY }}
          local_path: ${{ matrix.repos }}/${{ steps.pkgname.outputs.pkgname }}
          remote_path: '/home/repo-builder/tmp'

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: curl -u ${{ secrets.REPO_BUILDER_AUTH }} ${{ secrets.REPO_BUILDER_API }}/api/add-package/${{ steps.pkgname.outputs.pkgname }}
